"""Run manifests + auto-generated model cards (§4.6).

Every training command in Phases 8-11 records a manifest under ``runs/<id>/``
so any reported number is reproducible: the config snapshot, the git SHA, the
library versions, the resolved data paths, the seed, and ISO-8601 start/end
timestamps. The manifest is written atomically (temp file + rename) so a crashed
run never leaves a half-written JSON behind.
"""

from __future__ import annotations

import dataclasses
import json
import os
import platform
import subprocess
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import torch

from ..config import ExperimentConfig

__all__ = ["RunManifest", "git_sha", "new_run_id"]

MANIFEST_NAME = "manifest.json"
MODEL_CARD_NAME = "model_card.md"


def git_sha() -> str:
    """Current commit SHA, or ``"unknown"`` outside a git checkout."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def new_run_id(tag: str | None = None) -> str:
    """A sortable run id: ``YYYYmmdd-HHMMSS`` optionally suffixed with a tag."""
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    return f"{stamp}-{tag}" if tag else stamp


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


@dataclass
class RunManifest:
    """Reproducibility record for one training run.

    ``config`` holds a plain-dict snapshot of the `ExperimentConfig` (via
    `dataclasses.asdict`) so the manifest round-trips through JSON without
    needing the dataclass schema to reload.
    """

    run_id: str
    git_sha: str
    python_version: str
    torch_version: str
    numpy_version: str
    seed: int
    config: dict[str, Any]
    data_paths: list[str]
    start_time: str
    end_time: str | None = None
    metrics: dict[str, float] = field(default_factory=dict)

    @classmethod
    def create(
        cls,
        run_id: str,
        config: ExperimentConfig | dict[str, Any],
        data_paths: list[str],
        seed: int,
    ) -> RunManifest:
        """Build a manifest stamped with the current environment + start time."""
        config_dict = (
            dataclasses.asdict(config) if dataclasses.is_dataclass(config) else dict(config)
        )
        return cls(
            run_id=run_id,
            git_sha=git_sha(),
            python_version=platform.python_version(),
            torch_version=torch.__version__,
            numpy_version=np.__version__,
            seed=seed,
            config=config_dict,
            data_paths=list(data_paths),
            start_time=_now_iso(),
        )

    def finalize(self, metrics: dict[str, float] | None = None) -> None:
        """Stamp the end time and attach headline metrics."""
        self.end_time = _now_iso()
        if metrics:
            self.metrics.update(metrics)

    def write(self, run_dir: str | Path) -> Path:
        """Atomically write ``manifest.json`` and ``model_card.md`` under ``run_dir``.

        Returns the manifest path.
        """
        run_path = Path(run_dir)
        run_path.mkdir(parents=True, exist_ok=True)

        manifest_path = run_path / MANIFEST_NAME
        _atomic_write_text(manifest_path, json.dumps(dataclasses.asdict(self), indent=2))
        _atomic_write_text(run_path / MODEL_CARD_NAME, self.to_model_card())
        return manifest_path

    @classmethod
    def load(cls, path: str | Path) -> RunManifest:
        """Load a manifest from a ``manifest.json`` file (or its run dir)."""
        p = Path(path)
        if p.is_dir():
            p = p / MANIFEST_NAME
        with open(p) as fh:
            data = json.load(fh)
        return cls(**data)

    def to_model_card(self) -> str:
        """Render a minimal model card (Phase 15 supplies the richer template)."""
        metrics_lines = (
            "\n".join(f"- **{k}**: {v}" for k, v in self.metrics.items())
            if self.metrics
            else "_None recorded yet._"
        )
        data_lines = "\n".join(f"- `{p}`" for p in self.data_paths) or "_None._"
        return (
            f"# Model Card — run `{self.run_id}`\n\n"
            "Auto-generated by `memo` training (§4.6). Edit downstream, not here.\n\n"
            "## Provenance\n"
            f"- **Git SHA**: `{self.git_sha}`\n"
            f"- **Seed**: {self.seed}\n"
            f"- **Python**: {self.python_version}\n"
            f"- **PyTorch**: {self.torch_version}\n"
            f"- **NumPy**: {self.numpy_version}\n"
            f"- **Started**: {self.start_time}\n"
            f"- **Ended**: {self.end_time or '_in progress_'}\n\n"
            "## Data\n"
            f"{data_lines}\n\n"
            "## Metrics\n"
            f"{metrics_lines}\n"
        )


def _atomic_write_text(path: Path, text: str) -> None:
    """Write to a temp sibling then `os.replace` — never leave a partial file."""
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text)
    os.replace(tmp, path)
